Brickstorm\SolidRBundle\Entity\Action:
  type: entity
  table: b_solidr__action
  gedmo:
    translation:
      locale: locale
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
    quantity:
      type: float
    is_daily:
      nullable: true
      type: boolean
    is_weekly:
      nullable: true
      type: boolean
    is_monthly:
      nullable: true
      type: boolean
    is_yearly:
      nullable: true
      type: boolean
    is_public:
      default: false
      type: boolean
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToOne:
    user:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      cascade: {  }
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }