Brickstorm\SolidRBundle\Entity\Action:
  type: entity
  table: b_solidr__action
  gedmo:
    translation:
      locale: locale
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
    quantity:
      type: float
    is_daily:
      nullable: true
      type: boolean
    is_weekly:
      nullable: true
      type: boolean
    is_monthly:
      nullable: true
      type: boolean
    is_yearly:
      nullable: true
      type: boolean
    is_public:
      nullable: true
      default: false
      type: boolean
    orderNumber:
      nullable: true
      type: string
      unique: true
    amount:
      type: decimal
      precision: 2
      
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
  oneToOne:
    paymentInstruction:
      targetEntity: JMS\Payment\CoreBundle\Entity\PaymentInstruction
      joinColumn:
        name: paymentInstruction_id
        referencedColumnName: id
  oneToMany:
    updates:
      targetEntity: Update
      mappedBy: action
  manyToOne:
    project:
      targetEntity: Project
      cascade: {  }
      joinColumns:
        project_id:
          referencedColumnName: id
    user:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      cascade: {  }
      joinColumns:
        user_id:
          referencedColumnName: id
  lifecycleCallbacks: {  }