Brickstorm\SolidRBundle\Entity\Project:
  type: entity
  table: b_solidr__project
  gedmo:
    translation:
      locale: locale
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 250
      fixed: false
      gedmo:
        - translatable
        - sluggable
    description:
      type: text
      gedmo:
        - translatable
    unit_cost:
      nullable: true
      type: float
    quantity_wanted:
      nullable: true
      type: integer
    quantity_remaining:
      nullable: true
      type: integer
    devise:
      type: string
      length: 10
    slug:
      type: string
      length: 128
      gedmo:
        slug:
          separator: -
          style: default
          fields:
            - name
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToMany:
    medias:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinTable:
        name: b_solidr__project_medias
        joinColumns:
          media_id:
            referencedColumnName: id
        inverseJoinColumns:
          project_id:
            referencedColumnName: id
    cities:
      targetEntity: Brickstorm\WorldBundle\Entity\City
      joinTable:
        name: b_solidr__project_cities
        joinColumns:
          city_id:
            referencedColumnName: id
        inverseJoinColumns:
          project_id:
            referencedColumnName: id
    areas:
      targetEntity: Area
      joinTable:
        name: b_solidr__project_areas
        joinColumns:
          area_id:
            referencedColumnName: id
        inverseJoinColumns:
          project_id:
            referencedColumnName: id
  oneToMany:
    children:
      targetEntity: Project
      mappedBy: parent
    actions:
      targetEntity: Action
      mappedBy: project
  manyToOne:
    organization:
      targetEntity: Organization
      inversedBy: projects  
      joinColumns:
        organization_id:
          referencedColumnName: id
    parent:
      nullable: true
      targetEntity: Project
      inversedBy: children  
      joinColumns:
        parent_id:
          referencedColumnName: id
    creator:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      cascade: {  }
      joinColumns:
        creator_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }