Brickstorm\SolidRBundle\Entity\Update:
  type: entity
  table: b_solidr__update
  gedmo:
    translation:
      locale: locale
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
    parent_id:
      nullable: true
      type: integer
    name:
      type: string
      length: 250
      fixed: false
      gedmo:
        - translatable
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToOne:
    action:
      targetEntity: Action
      inversedBy: updates  
      joinColumns:
        action_id:
          referencedColumnName: id
  lifecycleCallbacks: {  }