homepage:
    pattern:  /
    defaults: { _controller: BrickstormSolidRBundle:Main:home }
cgvu:
    pattern:  /
    defaults: { _controller: BrickstormSolidRBundle:Main:cgvu }
contact_us:
    pattern:  /
    defaults: { _controller: BrickstormSolidRBundle:Main:contactus }
api_intro:
    pattern:  /
    defaults: { _controller: BrickstormSolidRBundle:Main:contactus }



#fbconnect
_security_login:
    pattern: /{_locale}/login
    defaults: { _controller: FOSUserBundle:Security:login }
    requirements:
        _locale: en|fr
_security_check:
    pattern:  /login_check
    defaults: { _controller: BrickstormSms4FoodBundle:User:loginCheck }
_security_check_fbconnect:
    pattern:  /login_check_fbconnect
    defaults: { _controller: BrickstormSms4FoodBundle:User:loginCheckFbconnect }